/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-legacy_cudaops
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_LEGACY_CUDAOPS_API_H
#define INCLUDED_LEGACY_CUDAOPS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_legacy_cudaops_EXPORTS
#define LEGACY_CUDAOPS_API __GR_ATTR_EXPORT
#else
#define LEGACY_CUDAOPS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_LEGACY_CUDAOPS_API_H */
