/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(copy.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4dd0830bf4640ca203fde30fcad9dc9f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <legacy_cudaops/copy.h>
// pydoc.h is automatically generated in the build directory
#include <copy_pydoc.h>

void bind_copy(py::module& m)
{

    using copy    = ::gr::legacy_cudaops::copy;


    py::class_<copy, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<copy>>(m, "copy", D(copy))

        .def(py::init(&copy::make),
           py::arg("batch_size"),
           py::arg("load"),
           py::arg("mem_model"),
           D(copy,make)
        )
        



        ;




}








